@baseUrl = http://127.0.0.1:8000
@paymentId = {{solicitarPagamento.response.body.$.id}}

# Execute cada bloco pelo link "Send Request" exibido pelo REST Client.
# Execute primeiro "Solicitar pagamento" para preencher {{paymentId}}.

### Solicitar pagamento

# @name solicitarPagamento
POST {{baseUrl}}/pagamentos
Content-Type: application/json

< ./requests/pagamento.json

### Consultar imediatamente: pagamento processando e cache MISS

GET {{baseUrl}}/pagamentos/{{paymentId}}
Accept: application/json

### Repetir imediatamente: pagamento processando e cache HIT

GET {{baseUrl}}/pagamentos/{{paymentId}}
Accept: application/json

### Após cerca de 20 segundos: processando e novo cache MISS

GET {{baseUrl}}/pagamentos/{{paymentId}}
Accept: application/json

### Após 30 segundos, antes do novo TTL expirar: HIT ainda processando

GET {{baseUrl}}/pagamentos/{{paymentId}}
Accept: application/json

### Após o novo TTL expirar: pagamento aprovado e cache MISS

GET {{baseUrl}}/pagamentos/{{paymentId}}
Accept: application/json

### Repetir imediatamente: pagamento aprovado e cache HIT

GET {{baseUrl}}/pagamentos/{{paymentId}}
Accept: application/json

### Enviar uma solicitação de pagamento inválida

POST {{baseUrl}}/pagamentos
Content-Type: application/json

< ./requests/pagamento-invalido.json

### Consultar um pagamento inexistente

GET {{baseUrl}}/pagamentos/00000000-0000-0000-0000-000000000000
Accept: application/json
